#!/usr/bin/env python
from colp import Color,HSV,HEX,RGB,by_name,detect_normalised #,get_last_processed
import argparse
import code
import os.path as op
import readline
import sys
banner = """
\033[95m┌─┐┌─┐┬  ┬─┐
\033[92m│  │ ││  │─┘
\033[93m└─┘┘─┘┆─┘┆   \x1b[6;30;42mthe color processor\x1b[0m
"""
if __name__ == '__main__': 
    parser = argparse.ArgumentParser(prog='colp' , description='Color Processor')
    parser.add_argument('-n'                     , '--no-banner'                  , action='store_true'                       , help='don\'t show  banner on interactive mode')
    parser.add_argument('-v'                     , '--visualizer'                 , help='visualize current color processed')
    parser.add_argument('-s'                     , '--simple-mode'                , action='store_true'                       , help='css-compliant output')
    parser.add_argument('-S'                     , '--scripting-mode'             , action='store_true'                       , default=True                                    , help='colp script output')
    # parser.add_argument('-d'                   , '--debug'                      ,                                           , help='stop ')
    parser.add_argument('-l'                     , '--load-script'                , metavar='SCRIPT_FILE'                     , help='load script from file or stdin')
    parser.add_argument('VAR'                    , nargs='*'                      , help='arbitrary python code execution')

    args = parser.parse_args()

    readlines = lambda filename: (sys.stdin if filename == '-' else open(filename, 'r')).\
            readlines()
    
    if args.load_script:
        exec(''.join(readlines(args.load_script)))

    for c in args.VAR:
        exec(c)

    Color.MODE = 'simple' if args.simple_mode else 'script'

    is_tty = sys.stdin.isatty()

    if args.visualizer:
        import tkinter as tk 
        root = tk.Tk()

    def readfunc(prompt):
        if is_tty and args.visualizer:
            root.configure(background=get_last_processed())
        return input('> ' if is_tty else '')

    code.interact(banner='' if args.no_banner or not is_tty else banner, \
            local=globals().update(locals()) or globals(), \
            readfunc=readfunc, \
            exitmsg='')
